/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import clock.IAlarmListener;
import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 *
 * @author dides
 */
public class MainViewJFrame extends javax.swing.JFrame {

    public boolean setEnableAlarm;

    /**
     * Creates new form MainJFrame
     */
    public MainViewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clock = new clock.ClockBean();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        computerServiceDataMenuItem = new javax.swing.JMenuItem();
        computersMenuItem = new javax.swing.JMenuItem();
        quitMenuItem = new javax.swing.JMenuItem();
        reportsMenu = new javax.swing.JMenu();
        printReportsMenuItem = new javax.swing.JMenuItem();
        ClockConfigurationMenu = new javax.swing.JMenu();
        clockNotificationsMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clock.setToolTipText("Clock time");

        fileMenu.setText("File");

        computerServiceDataMenuItem.setText("Computer service data...");
        computerServiceDataMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerServiceDataMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(computerServiceDataMenuItem);

        computersMenuItem.setText("Computers & Repairs...");
        fileMenu.add(computersMenuItem);

        quitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        quitMenuItem.setText("Quit");
        fileMenu.add(quitMenuItem);

        menuBar.add(fileMenu);

        reportsMenu.setText("Reports");

        printReportsMenuItem.setText("Print Reports...");
        reportsMenu.add(printReportsMenuItem);

        menuBar.add(reportsMenu);

        ClockConfigurationMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/campana.png"))); // NOI18N
        ClockConfigurationMenu.setToolTipText("Alarm clock setting");

        clockNotificationsMenuItem.setText("Notifications...");
        ClockConfigurationMenu.add(clockNotificationsMenuItem);

        menuBar.add(ClockConfigurationMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(504, Short.MAX_VALUE)
                .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(297, Short.MAX_VALUE)
                .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void computerServiceDataMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerServiceDataMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_computerServiceDataMenuItemActionPerformed

    public void setQuitMenuItemListener(ActionListener listener) {
        this.quitMenuItem.addActionListener(listener);
    }

    public void setAldComputerServiceMenuItemListener(ActionListener listener) {
        this.computerServiceDataMenuItem.addActionListener(listener);
    }

    public void setComputerMenuItemListener(ActionListener listener) {
        this.computersMenuItem.addActionListener(listener);
    }

    public void setClockNotificationsMenuItemListener(ActionListener listener) {
        this.clockNotificationsMenuItem.addActionListener(listener);
    }

    public int getHourAlarm() {
        return this.clock.getHourAlarm();
    }

    public void setHourAlarm(int hour) {
        this.clock.setHourAlarm(hour);
    }

    public int getMinutesAlarm() {
        return this.clock.getMinutesAlarm();
    }

    public void setMinutesAlarm(int min) {
        this.clock.setMinutesAlarm(min);
    }

    public String getMessage() {
        return this.clock.getMessage();
    }

    public void setMessage(String message) {
        this.clock.setMessage(message);
    }

    public boolean isEnableAlarm() {
        return this.clock.isEnableAlarm();
    }

    public void setEnableAlarm(boolean mode) {
        this.clock.setEnableAlarm(mode);
    }

    public boolean getMode() {
        return this.clock.isMode24();
    }

    public void setMode(boolean mode) {
        this.clock.setMode24(mode);
    }

    public void addAlarmListener(IAlarmListener receptor) {
        this.clock.addAlarmListener(receptor);
    }

    public void setReportsMenuItemListener(ActionListener listener) {
        this.printReportsMenuItem.addActionListener(listener);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ClockConfigurationMenu;
    private clock.ClockBean clock;
    private javax.swing.JMenuItem clockNotificationsMenuItem;
    private javax.swing.JMenuItem computerServiceDataMenuItem;
    private javax.swing.JMenuItem computersMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem printReportsMenuItem;
    private javax.swing.JMenuItem quitMenuItem;
    private javax.swing.JMenu reportsMenu;
    // End of variables declaration//GEN-END:variables
}
