/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.viewAldComputerService;

import java.awt.event.ActionListener;

/**
 *
 * @author barreirolistediego
 */
public class AldComputerServiceView extends javax.swing.JDialog {

    /**
     * Creates new form ALD_Computer_Services
     */
    public AldComputerServiceView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addressLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        establishmentNameLabel = new javax.swing.JLabel();
        numberOfEmployeesLabel = new javax.swing.JLabel();
        ALDComputerServicesLabel = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        numberOfEmployeesTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        establishmentNameTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        addressLabel.setText("Address:");

        phoneLabel.setText("Phone number:");

        establishmentNameLabel.setText("Establishment Name:");

        numberOfEmployeesLabel.setText("Number of Employees:");

        ALDComputerServicesLabel.setText("ALD_Computer_Services");

        phoneTextField.setToolTipText("phone number of the establishment");
        phoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTextFieldActionPerformed(evt);
            }
        });

        numberOfEmployeesTextField.setToolTipText("number of employees of the establishment");

        addressTextField.setToolTipText("establishment full address");

        establishmentNameTextField.setToolTipText("establishment name");
        establishmentNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                establishmentNameTextFieldActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(153, 255, 153));
        saveButton.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.setToolTipText("save data");
        saveButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 2, true)));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(255, 255, 153));
        editButton.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        editButton.setText("EDIT");
        editButton.setToolTipText("edit data");
        editButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 0), 2, true)));
        editButton.setEnabled(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(255, 102, 102));
        cancelButton.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        cancelButton.setText("CANCEL");
        cancelButton.setToolTipText("exit without saving");
        cancelButton.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true)));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ALDComputerServicesLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(establishmentNameLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(establishmentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(addressLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 2, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(numberOfEmployeesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numberOfEmployeesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(phoneLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(phoneTextField)))
                        .addGap(11, 11, 11)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ALDComputerServicesLabel)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(establishmentNameLabel)
                    .addComponent(establishmentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(addressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberOfEmployeesTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phoneLabel))
                    .addComponent(numberOfEmployeesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTextFieldActionPerformed

    private void establishmentNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_establishmentNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_establishmentNameTextFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    public void setSaveButtonItemActionListener(ActionListener listener) {
        this.saveButton.addActionListener(listener);
    }

    public void setEditButtonItemActionListener(ActionListener listener) {
        this.editButton.addActionListener(listener);
    }

    public void setCancelButtonItemActionListener(ActionListener listener) {
        this.cancelButton.addActionListener(listener);
    }

    public String getTextAddressTextField() {
        return this.addressTextField.getText();
    }

    public void setTextAddressTextField(String texto) {
        addressTextField.setText(texto);
    }

    public String getTextEstablishmentNameTextField() {
        return this.establishmentNameTextField.getText();
    }

    public void setTextEstablishmentNameTextField(String texto) {
        establishmentNameTextField.setText(texto);
    }

    public String getNumberOfEmployeesTextField() {
        return this.numberOfEmployeesTextField.getText();
    }

    public void setNumberOfEmployeesTextField(String texto) {
        numberOfEmployeesTextField.setText(texto);
    }

    public String getPhoneTextField() {
        return this.phoneTextField.getText();
    }

    public void setPhoneTextField(String texto) {
        phoneTextField.setText(texto);
    }

    public void setEnabledEditButton(boolean enabled) {
        this.editButton.setEnabled(enabled);
    }

    public void setEnabledSaveButton(boolean enabled) {
        this.saveButton.setEnabled(enabled);
    }

    public void setEnabledCancelButton(boolean enabled) {
        this.cancelButton.setEnabled(enabled);
    }

    public void setEditableAddressTextField(boolean editable) {
        this.addressTextField.setEditable(editable);
    }

    public void setEditableEstablishmentNameTextField(boolean editable) {
        this.establishmentNameTextField.setEditable(editable);
    }

    public void setEditableNumberOfEmployeesTextField(boolean editable) {
        this.numberOfEmployeesTextField.setEditable(editable);
    }

    public void setEditablePhoneTextField(boolean editable) {
        this.phoneTextField.setEditable(editable);
    }
    
     public void setAddress(String address) {
        this.addressTextField.setText(address);
    }

    public void setEstablishmentName(String establishmentName) {
        this.establishmentNameTextField.setText(establishmentName);
    }

    public void setPhone(String phone) {
        this.phoneTextField.setText(phone);
    }

    public void setNumberOfEmployees(String numEmployees) {
        this.numberOfEmployeesTextField.setText(numEmployees);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ALDComputerServicesLabel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel establishmentNameLabel;
    private javax.swing.JTextField establishmentNameTextField;
    private javax.swing.JLabel numberOfEmployeesLabel;
    private javax.swing.JTextField numberOfEmployeesTextField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

}
